def try_me():
    print("nothing to see here")
    print("nothing to see her")
    print("nothing to see he")
    print("nothing to see h")
    print("nothing to see")
    print("nothing to se")
    print("nothing to s")
    print("nothing to")
    print("nothing t")
    print("nothing")
    print("nothin")
    print("nothi")
    print("noth")
    print("not")
    print("no")
    print("n")
    print("")
    return None
